<?php
$escape = $this->plugin('escapeHtml');
$siteTitle = $site->title();
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($siteTitle)->setSeparator(' · ');
$this->headTitle()->append($this->setting('installation_title', 'Omeka S'));
// $this->headLink()->prependStylesheet($this->assetUrl('css/base_libnamic.css'));
// $this->headLink()->prependStylesheet($this->assetUrl('css/base_libnamic2.css'));
// $this->headLink()->prependStylesheet($this->assetUrl('css/mirador.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Open+Sans:400,400italic,600,600italic,700italic,700');
$this->headScript()->prependFile($this->assetUrl('js/default.js'));
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>
<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>

<head>
    <?php echo $this->headMeta(); ?>
    <?php echo $this->headTitle(); ?>
    <?php echo $this->headLink(); ?>
    <?php echo $this->headStyle(); ?>
    <?php echo $this->headScript(); ?>

    <!-- <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')) : ?>
            a:link,
            a:visited {
                color: <?php echo $accentColor; ?>
            }
            
            a:active,
            a:hover {
                color: <?php echo $accentColor; ?>;
                opacity: .75;
            }
            <?php endif; ?>
        </style> -->
</head>

<?php echo $this->htmlElement('body'); ?>
<?php echo $userBar; ?>
<!-- <nav> <p>Soy un navBar</p></nav> -->
<header>
    <div class="container">

        <ul class="slider">
            <li id="slide1">
                <img src="https://cdn.pixabay.com/photo/2015/11/27/20/28/florence-1066314_960_720.jpg" />
            </li>
            <li id="slide2">
                <img src="https://cdn.pixabay.com/photo/2014/02/05/11/31/vaulted-cellar-258906_960_720.jpg" />
            </li>
            <li id="slide3">
                <h1>Lorem ipsum dolor sit amet consectetur.</h1>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus cumque corrupti, quidem adipisci quia unde inventore quas repellat aut delectus facilis sapiente quam quos optio accusantium dolorum rerum laboriosam provident. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Earum consectetur, alias, eaque itaque voluptates nam dolorum, deleniti delectus doloribus quod illo laboriosam qui nihil explicabo laudantium nesciunt rerum sit tenetur.</p>
                <a href="omeka.libnamic">Omeka Theme by Libnamic</a>
            </li>
            <li id="slide4">
            <iframe width="100%" height="300" src="https://www.youtube.com/embed/ghQ5FG-7Z3w" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            </li>
        </ul>

        <ul class="menu">
            <li>
                <a href="#slide1"></a>
            </li>
            <li>
                <a href="#slide2"></a>
            </li>
            <li>
                <a href="#slide3"></a>
            </li>
            <li>
                <a href="#slide4"></a>
            </li>
        </ul>

    </div>

    <nav>
        <?php
        echo $site->publicNav()->menu()->renderMenu(null, [
            'maxDepth' => $this->themeSetting('nav_depth') - 1
        ]);
        ?>
    </nav>
</header>
<div id="content" role="main">
    <?php echo $this->content; ?>

</div>
<br>



<footer>




    <div class="desarrollador">

        <?php if ($footerContent = $this->themeSetting('footer')) : ?>
            <?php echo $footerContent; ?>
        <?php else : ?>
            <?php echo $this->translate('Desarrollado by Libnamic'); ?>
        <?php endif; ?>

    </div>
    <div class="logo"> </div>
    <a class="autor" href="omeka.libnamic.com"> Libnamic Digital Transformation</a>
    <span class="ir-arriba icon-arrow-up2">&#8679;</span>

</footer>
</body>

</html>